### ISSUE TITLE
svelte 3 work?

### ISSUE THREAD

**Issue by northkode** [nenadpnc/cl-editor#13]
any plans to make this work with svelte3?

**Comment by nenadpnc** [comment]
Hi @northkode, i'm planning this for a while, but tbh couldn't find time to implement it. If anybody wants to make a PR for it, i'm more than happy to help get that merged.

**Comment by northkode** [comment]
@nenadpnc  PR forr svelte 3 is up. 💃 
Fully works for us here, we are now using this in one of our projects 👍

**Comment by nenadpnc** [comment]
@northkode  Wonderfull 💯. I will have a look at it asap.

**Comment by nenadpnc** [comment]
I've published a new version, so i will close this issue. Again, thanks for the PR @northkode . 
#14

**Comment by northkode** [comment]
Your welcome !! 😁
