### ISSUE TITLE
Events don't seem to work

### ISSUE THREAD

**Issue by Omar-ABDELNABY** [nenadpnc/cl-editor#20]
I'm trying to wrap this into an angular component to use it in an angular project
I can't find a way to listen to change event, I followed the readme.md with something like this:
`editor.on('change', (html) => console.log(html));`
`editor.$on('change', (html) => console.log(html));`
and I got an error **Property 'on' does not exist on type 'Editor'**
![image](https://user-images.githubusercontent.com/45092562/83536701-dc677f80-a4f3-11ea-9483-ba74e8d5699b.png)

**Comment by Omar-ABDELNABY** [comment]
Any update on this?

**Comment by nenadpnc** [comment]
Hi @Omar-ABDELNABY thanks for reporting 👍 . Typescript definition file was not updated.
Correct syntax is `this.editor.$on('change', (event) => console.log(event))`.
Fixed in v2.1.0.
I've also updated Readme.md.
