### ISSUE TITLE
Feature request: remove format blockon second click if activated

### ISSUE THREAD

**Issue by tiloio** [nenadpnc/cl-editor#30]
**Current behavior**

When I click on a format block like `h1` (or something similar) I activate it.
I can't deactivate the format block with a second click.

**Wanted behavior**
When I click on a format block like `h1` (or something similar) I activate the style.
When my cursor is in the active `h1` element and I click the `h1` button again, I want that the format block is removed.

This should work for all format blocks.

**Comment by tiloio** [comment]
Maybe one of these answers will help: https://stackoverflow.com/questions/10810940/javascript-document-execcommand-remove-formatblock-formatting

**Comment by nenadpnc** [comment]
This kind of logic is meant to be implemented by consumer of the lib, to keep editor library lightweight.
```js
const editor = new Editor({
    target: document.getElementById('editor'),
    props: {
      actions: [
        {
            name: 'H1',
            icon: '<b>H<sub>1</sub></b>',
            title: 'Heading 1',
            result: () => {
             // set h1 heading
              editor.exec("formatBlock", "<H1>");
             // or, determine if current selection is <h1> and convert it to <div>
              editor.exec("formatBlock", "<div>");
            }
        }
      ],
    }
});
```
