### ISSUE TITLE
setHtml while viewHtml action is active doesn't replace contents?

### ISSUE THREAD

**Issue by Andersama** [nenadpnc/cl-editor#32]
When the viewHtml action is active setHtml edits $references.editor.innerHTML but that's not what is being currently displayed, when viewHtml is "deactivated" it replaces $references.editor.innerHTML with its current contents effectively discarding whatever setHtml calls were made.

Not sure if this is the intended behavior? Seems potentially broken.

**Comment by nenadpnc** [comment]
Yeah, you are right, it's a bug. I've just released a new version `2.2.0`, check it out, should fix the issue.

**Comment by Andersama** [comment]
Will do!
